name: publish to nuget
on:
  push:
    branches:
      - nuget
  release:
    types: [ published ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true
